### PR TITLE
Fix unchecked array casts causing server log spam

### LINKED ISSUE #10226: SpecialMobs Server Spam
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Kevlar Test Pack

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

I was expecting the console to not output random spam...growing my log file so often.

### The Reality

This is sort of the tail end of my log...this keeps spamming over and over and over. I've tried to /cofh killall and it reports many entities removed but this keeps spamming. This didn't happen prior to me updating to the Kevlar Test Pack. I do modify the config a bit because I'm forever traumatized from drowning creepers, however, the changes I've made have been there prior to Kevlar Test Pack so I would expect the server to not spit out this log after that update.

Does anyone recognize what is going on here or have any suggestions?

I've tried the following:
* Server Restart
* /cofh killall
* Remove SpecialMobs, start server, stop server, readd SpecialMobs, start server

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8578045/fml-server-latest.log)

### Your Proposal

Any advice or fix to this would be MUCH appreciated!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by eigenraven**
Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10226>

### CODE REVIEW

File: src/main/java/toast/specialMobs/MobHelper.java [hunk 1]
```diff
@@ -28,42 +26,37 @@
...
+import java.util.HashSet;
+import java.util.Objects;
+import java.util.stream.Stream;
+
 public abstract class MobHelper
 {
+    private static Stream<EntityAITaskEntry> typeFilteredTaskEntries(EntityLiving entity, Class<?> type) {
+        return Arrays.stream(entity.tasks.taskEntries.toArray())
+            .filter(Objects::nonNull)
+            .filter(e -> e instanceof EntityAITaskEntry)
```
Comment (Glease) [inline src/main/java/toast/specialMobs/MobHelper.java]: Pretty sure this list will only ever contain EntityAITaskEntry.

File: src/main/java/toast/specialMobs/MobHelper.java [hunk 2]
```diff
@@ -28,42 +26,37 @@
...
+            .map(e -> (EntityAITaskEntry) e)
+            .filter(e -> type.isInstance(e.action));
+    }
     // Clears all melee attack AIs.
     public static void clearMeleeAttackAI(EntityLiving entity) {
-        for (EntityAITaskEntry entry : (EntityAITaskEntry[]) entity.tasks.taskEntries.toArray()) if (entry.action.getClass().equals(EntityAIAttackOnCollide.class)) {
-            entity.tasks.removeTask(entry.action);
-        }
+        typeFilteredTaskEntries(entity, EntityAIAttackOnCollide.class).forEach(e -> entity.tasks.removeTask(e.action));
```
Comment (Glease) [inline src/main/java/toast/specialMobs/MobHelper.java:44]: If there are more than one matching entry this would probably result in a ConcurrentModificationException, which is probably why the original code want a toArray in the first place.

**Review by Glease — CHANGES_REQUESTED** [review]

File: src/main/java/toast/specialMobs/MobHelper.java (hunk 2 above)
Comment (eigenraven) [reply src/main/java/toast/specialMobs/MobHelper.java:44]: the function does `Arrays.stream(entity.tasks.taskEntries.toArray())`, so the copy is just moved to the caller

File: src/main/java/toast/specialMobs/MobHelper.java (hunk 1 above)
Comment (eigenraven) [reply src/main/java/toast/specialMobs/MobHelper.java]: The crashes and log spam indicates otherwise, ClassCastExceptions occur on exactly this list, trying to cast to EntityAITaskEntry

File: src/main/java/toast/specialMobs/MobHelper.java (hunk 2 above)
Comment (Glease) [reply src/main/java/toast/specialMobs/MobHelper.java:44]: Ah didn't notice. Sorry for that.

File: src/main/java/toast/specialMobs/MobHelper.java (hunk 1 above)
Comment (Glease) [reply src/main/java/toast/specialMobs/MobHelper.java]: It's a Java stupidness. If you don't call `toArray(new EntityAITaskEntry[0])` it will create a Object[]. Generic type information is not preserved.

Comment (eigenraven) [reply src/main/java/toast/specialMobs/MobHelper.java]: Should the code I just pushed avoid the exception then?

Comment (Glease) [reply src/main/java/toast/specialMobs/MobHelper.java]: Yeah it should be fine now.

**Review by Glease — APPROVED** [review]
